' Preview durch <Alt>d

@startuml Anwendungskern

interface Promise<T>

package @nestjs/common {
  class "@Injectable" as Injectable
  hide Injectable circle
}

package typeorm {
  class Repository<T>
}

package @nestjs/typeorm {
  class "@InjectRepository" as InjectRepository
  hide InjectRepository circle
}

package mail {
  class MailService
}

package buch {
  package entity {
    class Buch
  }

  package service #DDDDDD {
    class BuchInvalid
    class TitelExists
    class IsbnExists
    class VersionInvalid
    class VersionOutdated

    class BuchWriteService << control >> <<@Injectable()>> {
      + async create(buch: Buch): Promise<string|BuchInvalid|TitelExists|IsbnExists>
      + async update(id: number, buch: Buch, version: string): Promise<number|BuchInvalid|TitelExists|IsbnExists|VersionInvalid|VersionOutdated>
      + async delete(id: number): Promise<boolean>
    }

    BuchWriteService o--> "1" BuchValidationService: validationService
    BuchWriteService o--> "1" BuchReadService: readService
    BuchWriteService o--> "1" Repository: @InjectRepository repo
    BuchWriteService o--> "1" MailService: mailService

    BuchWriteService .up.> Injectable
    BuchWriteService .up.> InjectRepository

    BuchWriteService .up.> Promise
    BuchWriteService ..> Buch
    BuchWriteService .up.> BuchInvalid
    BuchWriteService .up.> TitelExists
    BuchWriteService .up.> IsbnExists
    BuchWriteService .up.> VersionInvalid
    BuchWriteService .up.> VersionOutdated

    BuchInvalid .up[hidden].> Buch
    Buch .up[hidden].> Promise
    Buch .up[hidden].> Injectable
    Buch .up[hidden].> InjectRepository
    TitelExists .up[hidden].> Buch
    BuchValidationService .[hidden].> Repository
    BuchValidationService .[hidden].> MailService
  }
}

hide empty members

footer (c) Jürgen Zimmermann

@enduml
