' Preview durch <Alt>d

@startuml Anwendungskern

interface Promise<T>

package @nestjs/common {
  class "@Injectable" as Injectable
  hide Injectable circle
}

package typeorm {
  class Repository<T>
}

package @nestjs/typeorm {
  class "@InjectRepository" as InjectRepository
  hide InjectRepository circle
}

package buch {
  package entity {
    class Buch
  }

  package service #DDDDDD {
    class QueryBuilder

    class BuchReadService << control >> <<@Injectable()>> {
      + async findById(id: number): Promise<Buch | undefined>
      + async find(suchkriterien?: Record<string, any>): Promise<Buch[]>
    }

    BuchReadService o--> "1" QueryBuilder: queryBuilder
    BuchReadService o--> "1" Repository: @InjectRepository repo

    BuchReadService .up.> Injectable
    BuchReadService .up.> InjectRepository

    BuchReadService .up.> Promise
    BuchReadService ..> Buch

    QueryBuilder .[hidden].> Repository
    QueryBuilder .[hidden].> Buch
  }
}

hide empty members

footer (c) Jürgen Zimmermann

@enduml
