' Preview durch <Alt>d

@startuml Komponenten

left to right direction

actor RESTClient
actor GraphQLClient

node "Nest" {
  [RequestLoggerMiddleware]

  [BuchController]
  [BuchResolver]

  [BuchService]

  [Repository<Buch>]

  [MailService]
}


cloud {
    [TypeORM]
}

cloud {
    [nodemailer]
}

database "DB buch" {
    [Tabelle buch]
    [Tabelle titel]
    [Tabelle abbildung]
}

node {
    [Mailserver]
}

RESTClient ~~> [RequestLoggerMiddleware]
GraphQLClient ~~> [RequestLoggerMiddleware]

[RequestLoggerMiddleware] ~~> [BuchController]
[RequestLoggerMiddleware] ~~> [BuchResolver]

[BuchController] ..> [BuchService]
[BuchResolver] ..> [BuchService]
[BuchService] ..> [Repository<Buch>]

[Repository<Buch>] ~~> [TypeORM]
[TypeORM] ~~> [Tabelle buch]
[TypeORM] ~~> [Tabelle titel]
[TypeORM] ~~> [Tabelle abbildung]

[BuchService] ..> [MailService]
[MailService] ~~> [nodemailer]
[nodemailer] ~~> [Mailserver]

footer (c) Jürgen Zimmermann

@enduml
