' Preview durch <Alt>d

@startuml Komponenten

left to right direction

actor RESTClient
actor GraphQLClient

node "Nest" {
  [RequestLoggerMiddleware]

  [AlbumController]
  [AlbumResolver]

  [AlbumService]

  [Repository<Album>]

  [MailService]
}


cloud {
    [TypeORM]
}

cloud {
    [nodemailer]
}

database "DB album" {
    [Tabelle album]
    [Tabelle kuenstler]
    [Tabelle lied]
}

node {
    [Mailserver]
}

RESTClient ~~> [RequestLoggerMiddleware]
GraphQLClient ~~> [RequestLoggerMiddleware]

[RequestLoggerMiddleware] ~~> [AlbumController]
[RequestLoggerMiddleware] ~~> [AlbumResolver]

[AlbumController] ..> [AlbumService]
[AlbumResolver] ..> [AlbumService]
[AlbumService] ..> [Repository<Album>]

[Repository<Album>] ~~> [TypeORM]
[TypeORM] ~~> [Tabelle album]
[TypeORM] ~~> [Tabelle kuenstler]
[TypeORM] ~~> [Tabelle lied]

[AlbumService] ..> [MailService]
[MailService] ~~> [nodemailer]
[nodemailer] ~~> [Mailserver]

footer (c) Gruppe 4

@enduml
