// Preview durch <Strg><Shift>v

= Projekthandbuch
Melvin Grzalik <grme1011@h-ka.de> https://www.h-ka.de
Niklas Justus <juni1016-ka.de> https://www.h-ka.de
Mike Tran <trmi1016@h-ka.de> https://www.h-ka.de
Konstantin Kraus <krko1012@h-ka.de> https://www.h-ka.de
:doctype: book
:toc: left
:sectanchors:
:sectlinks:
:sectnums:
:source-highlighter: highlight.js
:icons: font
// :kroki-server-url: https://kroki.io

// https://github.com/asciidoctor/asciidoctorj
// https://github.com/asciidoctor/asciidoctor-diagram
// http://de.plantuml.com/classes.html
// http://de.plantuml.com/component.html
// https://github.com/odrotbohm/asciidoctor-plantuml

== Der Applikationsserver

=== Der Applikationsserver im Überblick

Sed porttitor lectus nibh. Nulla porttitor accumsan tincidunt.

.Use Cases
[plantuml,use-cases,svg]
----
include::use-cases.plantuml[]
----

Quisque velit nisi, pretium ut lacinia in, elementum id enim. Nulla porttitor
accumsan tincidunt.

.Komponentendiagramm
[plantuml,komponenten,svg]
----
include::komponenten.plantuml[]
----

=== Die REST-Schnittstelle

Realisierung der Rest Endpunkte, für Lese- und Schreibzugriffe

."AlbumGetController" für Lesezugriffe an der REST-Schnittstelle
[plantuml,AlbumGetController,svg]
----
include::AlbumGetController.plantuml[]
----

."Sequenzdiagramm" mit den Methodenaufrufen
[plantuml,sequenzdiagramm,svg]
----
include::sequenzdiagramm.plantuml[]
----

."AlbumWriteController" für Schreibzugriffe an der REST-Schnittstelle
[plantuml,AlbumGetController,svg]
----
include::AlbumWriteController.plantuml[]
----

=== Die GraphQL-Schnittstelle

Realisierung des GraphQL Endpunktes POST für Lese- und Schreibzugriffe.

.AlbumQueryResolver für Lesezugriffe an der GraphQL-Schnittstelle
[plantuml,AlbumQueryResolver,svg]
----
include::AlbumQueryResolver.plantuml[]
----

.AlbumMutationResolver für Schreibzugriffe an der GraphQL-Schnittstelle
[plantuml,AlbumMutationResolver,svg]
----
include::AlbumMutationResolver.plantuml[]
----

=== Die Geschäftslogik

Verarbeitung der einzelnen Geschäftsprozesse.

."AlbumReadService" von der Geschäftslogik
[plantuml,AlbumReadService,svg]
----
include::AlbumReadService.plantuml[]
----

."AlbumWriteService" von der Geschäftslogik
[plantuml,AlbumWriteService,svg]
----
include::AlbumWriteService.plantuml[]
----

=== Klasse für Entities

.Entity
[plantuml,Album,svg]
----
include::Album.plantuml[]
----

=== ER-Diagramm

.ER-Diagramm
[plantuml,ER-Diagramm,svg]
----
include::ER-Diagramm.plantuml[]
----
