' Preview durch <Alt>d

@startuml Sequenzdiagramm

actor Gast

boundary AlbumGetController
control AlbumReadService
database album

Gast -> AlbumGetController : GET / getById()
AlbumGetController -> AlbumReadService: findById()
AlbumReadService -> album: [TypeORM]

footer (c) Gruppe 4

@enduml
