' Preview durch <Alt>d

@startuml Sequenzdiagramm

actor Gast

boundary BuchGetController
control BuchReadService
database buch

Gast -> BuchGetController : GET / getById()
BuchGetController -> BuchReadService: findById()
BuchReadService -> buch: [TypeORM]

footer (c) Jürgen Zimmermann

@enduml
