' Preview durch <Alt>d

@startuml Use Cases

actor Gast
actor Admin
actor Musikredakteur

rectangle album {
    Gast --> (Album suchen)
    Admin --> (Album suchen)
    Admin --> (Album anlegen)
    Admin --> (Album ändern)
    Admin --> (Album löschen)
    Musikredakteur --> (Album suchen)
    Musikredakteur --> (Album anlegen)
    Musikredakteur --> (Album ändern)
}

footer (c) Gruppe 4 

@enduml
