' Preview durch <Alt>d

@startuml Use Cases

actor Gast
actor Admin
actor Kunde

rectangle buch {
    Gast --> (Buch suchen)
    Admin --> (Buch suchen)
    Admin --> (Buch anlegen)
    Admin --> (Buch ändern)
    Admin --> (Buch löschen)
    Kunde --> (Buch suchen)
    Kunde --> (Buch anlegen)
    Kunde --> (Buch ändern)
}

footer (c) Jürgen Zimmermann

@enduml
