' Preview durch <Alt>d

@startuml Use Cases

actor Gast
actor Admin
actor Kunde

rectangle album {
    Gast --> (Album suchen)
    Admin --> (Album suchen)
    Admin --> (Album anlegen)
    Admin --> (Album ändern)
    Admin --> (Album löschen)
    Kunde --> (Album suchen)
    Kunde --> (Album anlegen)
    Kunde --> (Album ändern)
}

footer (c) Gruppe 4 

@enduml
